version: "3.7"
services:
  ### DB START
  # This is the database to which the all the other components in the stack will connect and interact with
  # (but mostly it's PostgREST that is going to be responsible for the bulk of the db traffic)
  # Having the database in a container is very convinient in development but in production you will
  # use a separate database instance, like Amazon RDS, i.e. in production this section will be
  # commented and in the .env file you will specify the ip of your separate database instance
#  testTaskCheckbox:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    image: youtubetapi:0.1
#    hostname: fastapi
#    ports:
#      - ${FASTAPI_INTERNAL_PORT}:${FASTAPI_EXTERNAL_PORT}
#    networks:
#      - sever_infrastructure
#    env_file:
#      - .env
#    volumes:
#      - ./server:/app/server
#    depends_on:
#      - pgadmin
#      - dbpsql
#      - celery
#      - flower

  dbpsql:
    image: postgres:13.14-bullseye
    container_name: postgres_database_checks
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    restart: always
    hostname: ${POSTGRES_HOST}
    networks:
      - app_infrastructure
    ports:
      - ${POSTGRES_INGRESS_PORT}:${POSTGRES_PORT}
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - postgres_data_prod:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg4_l_checks
    restart: unless-stopped
    hostname: ${PGADMIN_HOST_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_INGRESS_PORT}:${PGADMIN_CONTAINER_PORT}
    depends_on:
      - dbpsql
    networks:
      - app_infrastructure

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    hostname: ${REDIS_HOST_NAME}
    environment:
      RI_APP_PORT: ${REDIS_PORT}
      RI_APP_HOST: ${REDIS_HOST}
      RI_ENCRYPTION_KEY: ${REDIS_ENCRYPTION_KEY}
      RI_LOG_LEVEL: ${REDIS_LOG_LEVEL}
    networks:
      - app_infrastructure
    ports:
      - ${REDIS_INGRESS_PORT}:${REDIS_PORT}
    volumes:
      - redis_logs:/data/logs
#  nginx:
#    build: ./nginx
#    container_name: nginx_checks
#    hostname: ${NGINX_HOST_NAME}
#    volumes:
#      - templates_nginx:/etc/nginx/templates
#    ports:
#      - ${NGINX_INGRESS_PORT}:${NGINX_CONTAINER_PORT}
#    environment:
#      NGINX_PORT: ${NGINX_CONTAINER_PORT}
#    depends_on:
#      - pgadmin
#      - dbpsql
#    networks:
#      - app_infrastructure

networks:
  app_infrastructure:

volumes:
  postgres_data_prod:
    name: postgres_data_prod
#  templates_nginx:
#    name: templates_nginx
  redis_logs:
    name: redis_logs