"""Add app tables

Revision ID: 12f85798732a
Revises: 
Create Date: 2024-05-04 08:58:53.492764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12f85798732a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("product_identifier", sa.Uuid(), nullable=False),
        sa.Column("product_title", sa.String(), nullable=False),
        sa.Column("product_description", sa.String(), nullable=False),
        sa.Column("product_units", sa.String(), nullable=False),
        sa.Column("product_min_quantity_sell", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("registration_datetime", sa.DateTime(), nullable=False),
        sa.Column("last_login_datetime", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "product_price",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("discount", sa.Numeric(), nullable=False),
        sa.Column("discount_update", sa.DateTime(), nullable=False),
        sa.Column("price_update", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_price_id"), "product_price", ["id"], unique=False)
    op.create_table(
        "stock",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity_in_stock", sa.Float(), nullable=False),
        sa.Column("stock_last_update", sa.DateTime(), nullable=False),
        sa.Column("stock_product_identifier", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_id"), "stock", ["id"], unique=False)
    op.create_table(
        "user_essence",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_essence_id"), "user_essence", ["id"], unique=False)
    op.create_table(
        "checks",
        sa.Column("check_datetime", sa.DateTime(), nullable=False),
        sa.Column("check_identifier", sa.Uuid(), nullable=False),
        sa.Column("check_total_price", sa.Numeric(), nullable=False),
        sa.Column("check_purchasing_method", sa.Enum("card", "cash", native_enum=False), nullable=False),
        sa.Column("check_user_essence", sa.Integer(), nullable=False),
        sa.Column("check_stock_id", sa.Integer(), nullable=False),
        sa.Column("check_exchange", sa.Numeric(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["check_stock_id"], ["stock.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["check_user_essence"], ["user_essence.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_checks_id"), "checks", ["id"], unique=False)
    op.create_table(
        "sold_products",
        sa.Column("sold_product_title", sa.String(), nullable=False),
        sa.Column("sold_product_description", sa.String(), nullable=False),
        sa.Column("sold_discount", sa.Numeric(), nullable=False),
        sa.Column("sold_price", sa.Numeric(), nullable=False),
        sa.Column("sold_units", sa.String(), nullable=False),
        sa.Column("sold_quantity", sa.Float(), nullable=False),
        sa.Column("sold_datetime", sa.DateTime(), nullable=False),
        sa.Column("sold_total_price", sa.Numeric(), nullable=False),
        sa.Column("sold_check_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["sold_check_id"],
            ["checks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sold_products_id"), "sold_products", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sold_products_id"), table_name="sold_products")
    op.drop_table("sold_products")
    op.drop_index(op.f("ix_checks_id"), table_name="checks")
    op.drop_table("checks")
    op.drop_index(op.f("ix_user_essence_id"), table_name="user_essence")
    op.drop_table("user_essence")
    op.drop_index(op.f("ix_stock_id"), table_name="stock")
    op.drop_table("stock")
    op.drop_index(op.f("ix_product_price_id"), table_name="product_price")
    op.drop_table("product_price")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
