"""seed fixv5

Revision ID: 35e928c3fe4c
Revises: 17a36e73e45f
Create Date: 2024-05-05 20:10:49.318610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35e928c3fe4c"
down_revision: Union[str, None] = "17a36e73e45f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("sold_products", "sold_product_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("sold_products", "sold_product_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
