"""seed fixv3

Revision ID: eb0fe0bb4e51
Revises: cf81fb0f2d98
Create Date: 2024-05-04 21:51:52.873270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb0fe0bb4e51"
down_revision: Union[str, None] = "cf81fb0f2d98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("checks", sa.Column("check_rest", sa.Numeric(), nullable=False))
    op.drop_column("checks", "check_exchange")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("checks", sa.Column("check_exchange", sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column("checks", "check_rest")
    # ### end Alembic commands ###
